### ISSUE TITLE
'UIMenuController' was deprecated in iOS 16.0: UIMenuController is deprecated. Use UIEditMenuInteraction instead.

### ISSUE THREAD

**Issue by TrabelsiAchraf** [PDFTron/pdftron-ios-samples#18]
We use PDFTron for our app, and recently we migrate to iOS 17 with minium iOS 16, and we are obsessed to not have warning in our project, bu unfortunately we have 1 warning related to PDFTron  : 'UIMenuController' was deprecated in iOS 16.0: UIMenuController is deprecated. Use UIEditMenuInteraction instead. Is there any chance to fix this please ?

'UIMenuController' was deprecated in iOS 16.0: UIMenuController is deprecated. Use UIEditMenuInteraction instead.

**Comment by dluco** [comment]
Thank you for getting in touch with this issue - we can look into the deprecation warning in the SDK.

This issue itself will be closed as it is not directly related to this repository of samples. If you would like to raise the issue up further, you can get in touch via our Technical Support.
